sudo: false
language: node_js
cache: yarn
script: yarn ci
node_js:
  - "7"
  - "6"
  - "4"
env:
  - CXX=g++-4.8
branches:
  only:
    - master
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
